### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by majinmartin93** [tuxuser/py-xbox-webapi#1]
when i try to load the script i get this error
  File "/Library/Python/2.7/site-packages/xbox_webapi-0.0.1-py2.7.egg/xbox_webapi/common/enum.py", line 18
    class Enum(metaclass=EnumType):
                        ^
SyntaxError: invalid syntax

**Comment by tuxuser** [comment]
Oops, it's actually including the Enum class of xbox-webapi instead of LUFA's..
